<?php

namespace AppBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAmountOfMessages()
    {
        return intval($this->createQueryBuilder('message')
        ->select('COUNT(message)')
        ->getQuery()->getSingleScalarResult());
    }

}
